# k8s/monitoring/crds-patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply to all CRDs
resources:
  - ../base

patches:
  # Remove annotations from ALL CRDs
  - patch: |
      - op: remove
        path: /metadata/annotations
    target:
      kind: CustomResourceDefinition