# k8s/monitoring/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# The Helm chart that Kustomize should pull and template
  
helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.46.0 # Must match your target version
    releaseName: loki
    namespace: monitoring # Set the namespace for the deployed resources
    # Specify the local values file to override chart defaults
    valuesFile: loki-values.yaml

