# k8s/monitoring/crds/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Use a remote resource to grab the CRDs from the chart
resources:
  - namespace.yaml
  - grafana-certificate.yaml
  - prometheus-certificate.yaml
  - alertmanager-certificate.yaml

