# k8s/monitoring/prometheus-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: monitoring
spec:
  secretName: prometheus-tls
  duration: 2160h   # 90 days
  renewBefore: 360h # 15 days
  commonName: prometheus.myapp.localdev.me
  dnsNames:
    - prometheus.myapp.localdev.me
  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer