apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  #- service-monitor.yaml
labels:
  - pairs:
      app.kubernetes.io/name: sample-app
      app.kubernetes.io/part-of: myapp
commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
#namespace: default

# Labels applied to all base resources.
# Annotations keep Argo CD sync ordering.