# k8s/overlays/dev/patch-service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app
  namespace: dev          # <-- forces the namespace to 'dev'
spec:
  selector:
    matchLabels:
      app: dev-sample-app   # <-- overrides the matchLabels to select dev pods 