# k8s/overlays/staging/patch-service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app
  namespace: staging          # <-- forces the namespace to 'staging'  
spec:
  namespaceSelector:
    matchNames:
      - staging # Only scrape targets in the 'staging' namespace